export { default as ConnectEmailPage } from './connectEmailPage/ConnectEmailPage';
export { default as CookiePolicyPage } from './cookies/CookiePolicyPage';
export { default as GetSubscriptionPage } from './getSubscription/GetSubscriptionPage';
export { default as LandingPage } from './landing/LandingPage';
export { default as LocationsPage } from './locations/LocationsPage';
export { default as ConfirmPage } from './login/confirm/ConfirmPage';
export { default as LoginPage } from './login/LoginPage';
export { default as MyIpPage } from './myIp/MyIpPage';
export { default as PaddleCheckoutPage } from './paddleCheckout/PaddleCheckoutPage';
export { ProtectedPaddleCheckoutPage } from './paddleCheckout/protected';
export { PublicPlansPage } from './plans/PlansPage';
export { default as PricingPage } from './pricing/PricingPage';
export { default as PrivacyPolicyPage } from './privacy/PrivacyPolicyPage';
export { default as AffiliatePage } from './profile/affiliate/AffiliatePage';
export { ProtectedDevicesPage } from './profile/devices/protected';
export { ProtectedExtraDevicePurchasePage } from './profile/devices/protected-extra-device';
export { ProtectedMenuPage } from './profile/menu/protected';
export { ProtectedReferralsPage } from './profile/menu/referrals/protected';
export { ProtectedTransactionsPage } from './profile/menu/transactions/protected';
export { ProtectedTransactionDetailsPage } from './profile/menu/transactions/protected-details';
export { ProtectedPaymentPage } from './profile/payment/protected';
export { ProtectedPlansPage } from './profile/plans/protected';
export { ProtectedProfileSubscriptionPage } from './profile/subscription/protected';
export { default as ReferralsPage } from './referrals/ReferralsPage';
export { default as SubscriptionFailPage } from './subscriptionFail/SubscriptionFailPage';
export { default as SubscriptionSuccessPage } from './subscriptionSuccess/SubscriptionSuccessPage';
export { default as TermsPage } from './terms/TermsPage';
export { default as WhatIsVpnPage } from './whatIsVpn/WhatIsVpnPage';
