export const apiRoutes = {
  analytics: {
    trackEvent: '/events',
    trackUserCreated: '/events/user-created',
  },
  bot: {
    notifyPayment: '/notify/payment',
    notifyUserEvent: '/notify/user-event',
    notifyUserRewarded: '/notify/user-rewarded',
    telegramSticker: (fileId: string) => `/telegram/sticker/${fileId}`,
  },
  broadcasts: {
    collection: '/',
    byId: (id: number | string) => `/${id}`,
    messages: (broadcastId: number | string) => `/${broadcastId}/messages`,
    messagesBatch: (broadcastId: number | string) => `/${broadcastId}/messages/batch`,
  },
  payments: {
    stripeCreateSession: '/stripe/create-session',
    stripeSubscription: '/stripe/subscription',
    stripeWebhook: '/stripe/webhook',
    yookassaCreateSession: '/yookassa/create-session',
    yookassaWebhook: '/yookassa/webhook',
    yookassaSavedMethods: '/yookassa/saved-methods',
    yookassaSavedMethodById: (id: string) => `/yookassa/saved-methods/${encodeURIComponent(id)}`,
    telegramStarsCreateInvoice: '/telegram-stars/create-invoice',
    telegramStarsPaymentSucceeded: '/telegram-stars/payment-succeeded',
    plans: '/plans',
    promoValidate: '/promo/validate',
    toltReferral: '/tolt/referral',
    toltClick: '/tolt/click',
    myTransactions: '/my-transactions',
    searchPayments: '/search',
    hasEverPaid: '/internal/has-ever-paid',
    remnawaveEvent: '/remnawave-event',
  },
  referrals: {
    collection: '/',
    byInvited: (userId: string) => `/by-invited/${encodeURIComponent(userId)}`,
    rewardAfterPayment: '/reward-after-payment',
  },
  remnawave: {
    // ── server-to-server (InterServiceGuard) ─────────────────────────────
    users: '/users',
    userByTelegramId: (telegramId: number | string) => `/users/by-telegram-id/${telegramId}`,
    userByEmail: (email: string) => `/users/by-email/${encodeURIComponent(email)}`,
    userById: (userId: number) => `/users/${userId}`,
    revokeUserSubscription: (userId: number) => `/users/${userId}/actions/revoke`,
    subscriptionSubpageConfig: (shortUuid: string) => `/subscriptions/subpage-config/${shortUuid}`,
    subscriptionInfoByShortUuid: (shortUuid: string) => `/sub/${shortUuid}/info`,
    subscriptionPageConfig: (uuid: string) => `/subscription-page-configs/${uuid}`,
    userDevices: (userId: number) => `/users/${userId}/devices`,
    userDevice: (userId: number, hwid: string) =>
      `/users/${userId}/devices/${encodeURIComponent(hwid)}`,
    telegramPhoto: (telegramId: number | string) => `/users/telegram-photo/${telegramId}`,
    userExtraDevice: (userId: number) => `/users/${userId}/extra-device`,
    userExpiry: (userId: number) => `/users/${userId}/expiry`,
    userMetadata: (userId: number) => `/users/${userId}/metadata`,
    // ── client-facing (ClientUserGuard — no user id in path) ──────────────
    me: '/users/me',
    meMetadata: '/users/me/metadata',
    meDevices: '/users/me/devices',
    meDevice: (hwid: string) => `/users/me/devices/${encodeURIComponent(hwid)}`,
    meTelegramPhoto: '/users/me/telegram-photo',
    meLinkEmail: '/users/me/link-email',
    // ── TMA registration (TelegramCredentialGuard — user may not exist yet) ─
    connectEmail: '/users/connect/email',
  },
} as const;
